id: 5cf6dabf8ed142feb9397f410c54204f
initial_creation_type: ocr
source_metadata:
  volumes:
    e19daaa34fc1462490a2bf6c45de1eee:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
